BanglaChat/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.conf import settings
from posts_app import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login_app.urls')),
    path('home/',include('posts_app.urls')),
    path('',views.home, name='home')
]

urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

login_app/urls.py
from django.urls import path
from . import views
app_name ='login_app'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('', views.log_in, name='login'),
    path('edit_profile/', views.Edit_profile, name='edit_profile'),
    path('user_logout/', views.logout_user, name='log_out'),
    path('user/', views.user, name='user'),
]

posts_app/urls.py
from django.urls import path
from . import views 

app_name='posts_app'

urlpatterns = [
    path('',views.home, name='home'),
]

login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE, related_name='user_profile')
    Profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    full_name = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)
    dob = models.DateField(blank=True, null= True)
    website = models.URLField(blank= True)
    
class Follow(models.Model):
    follower = models.ForeignKey(User,on_delete= models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete= models.CASCADE, related_name='following')
    following_date= models.DateTimeField(auto_now_add= True)

posts_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    author= models.ForeignKey(User, on_delete= models.CASCADE, related_name='post_pic')
    image = models.ImageField(upload_to ='posted_pic')
    caption = models.CharField(max_length=264)
    upload_date = models.DateTimeField(auto_now_add = True)
    
    class Meta:
        ordering= ['-upload_date']
        
    def __str__(self):
        return self.author
        
class Likes(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_post')
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name='liker')
    
    def __str__(self):
        return self.user

login_app/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile

class NewUserForm(UserCreationForm):
    email = forms.EmailField(label='', widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    password2 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))
    class Meta:
        model = User
        fields = ('username', 'email', 'password1','password2')


class EditProfile(forms.ModelForm):
    dob= forms.DateField(widget=forms.TextInput(attrs={'type':'date'}),required=False)
    class Meta:
        model = UserProfile
        exclude = ('user',)

posts_app/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('image','caption')

login_app/views.py
from django.shortcuts import render,HttpResponseRedirect, redirect
from django.views.generic import TemplateView, CreateView
from .forms import NewUserForm, EditProfile
from django.contrib.auth.forms import AuthenticationForm
from .models import UserProfile
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from posts_app.models import Post
from posts_app.forms import PostForm
# Create your views here.

def sign_up(request):
    form = NewUserForm()
    registered = False
    if request.method == 'POST':
        form = NewUserForm(data=request.POST)
        if form.is_valid():
            user = form.save(commit=True)
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('login_app:login'))
    diction = {'form':form, 'title':'Sign Up'}
    return render(request, 'login_app/signup.html', context=diction)


def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user=authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('posts_app:home'))
    diction = {'title':'Log in','form':form}
    return render(request, 'login_app/login.html', context=diction )

@login_required
def Edit_profile(request):
    current_user = UserProfile.objects.get(user= request.user)
    form = EditProfile()
    form = EditProfile(instance=current_user)
    if request.POST== 'POST':
        form = EditProfile(request.POST,request.FILES, instance=current_user)
        if form.is_valid():
            form.save()
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('login_app:user'))
    diction= {'form':form}
    return render(request, 'login_app/profile.html', context=diction)


@login_required
def logout_user(request):
    logout(request)
    return redirect('login_app:login')
@login_required
def user(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post=form.save(commit=False)
            post.author= request.user
            post.save()
            return redirect('posts_app:home')
    diction = {'form':form, 'title':'post'}
    return render(request, 'login_app/user.html', context= diction)

posts_app/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def home(request):
    return render(request,'posts_app/home.html')

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Bangla Chat {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
  <body>
    
      <div class="container d-flex justify-content-center mt-5 mb-5">
        {% block content %}
        {% endblock %}
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

templates/login_app/login.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="form ">
    <form action="" method="POST">
        <div class="mb-3">
            <h3 style="text-align: center;">Bangla Chat</h3>
            <p>Sign in to see photos and videos from your friends.</p>
            {{form | crispy  }}
            {% csrf_token %}
        </div>
        
        <button type="submit" class="btn btn-primary button mb-2" >Log In</button>
        <h5>Don't have an account? <a href="{% url 'login_app:signup'%}" style="text-decoration: none;">Sign Up</a></h5>
      </form>
      
      
</div>
{% endblock %}

templates/login_app/profile.html
{% extends 'navbar.html'%}
{% load crispy_forms_tags %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="">
    <form action="" method="POST" enctype="multipart/form-data">
        <div class="mb-3">
            <h3 style="text-align: center;">Upload Your Profile picture</h3>
            
            {{form | crispy  }}
            {% csrf_token %}
        </div>
        
        <button type="submit" class="btn btn-primary button mb-2" >Upload</button>
        <h5><a href="{% url 'posts_app:home'%}" style="text-decoration: none;">Skip</a></h5>
      </form>
      
      
</div>
{% endblock %}

templates/login_app/signup.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title %} {{title}}{% endblock %}


{% block content %}

<div class="form ">
    <form action="" method="POST">
        <div class="mb-3">
            <h3 style="text-align: center;">Bangla Chat</h3>
            <p>Sign up to see photos and videos from your friends.</p>
            {{form | crispy  }}
            {% csrf_token %}
        </div>
        
        <button type="submit" class="btn btn-primary button mb-2" >Sign up</button>
        <h4>Have an account? <a href="{% url 'login_app:login'%}" style="text-decoration: none;">Log in</a></h4>
      </form>
      
      
</div>


{% endblock %}

templates/login_app/user.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title %} {{user.user_profile.full_name}} {% endblock %}
{% block content %}
<div class="row d-flex">
    <div class="col-4  ">
        {%if user.user_profile.Profile_pic %}
        <img class="bg-secondary rounded-circle" src="/media/{{user.user_profile.Profile_pic}}" alt="" width="220px" height="220px">
        {% else %}
        <img src="/media/demo.png" alt="" width="220px" height="220px">
        {% endif %}
        <br>
        <br>
        <br>
        <hr>
        
    </div>
    <div class="col-4 text-center">
        <h3>{{user.username}} &nbsp; <a href="{% url 'login_app:edit_profile' %}" class="btn btn-light">Edit profile</a></h3>
        <h5>{{user.post_pic.count}} posts &nbsp;&nbsp; {{user.following.count}} followers &nbsp;&nbsp; {{user.follower.count}} following </h5>
        <br>
        <br>
        <h6>{{user.user_profile.full_name}}</h6>
        <p>{{user.user_profile.description}}</p>
        
        
    </div>
    <div class="col-4">
        
    </div>
</div>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    post
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form | crispy }}
            <button type="submit" class="btn btn-primary mb-2">Save</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/navbar.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Bangla Chat {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'posts_app:home'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login_app:log_out'%}">Log out</a>
              </li>
              <li class="nav-item">
                {% if user.user_profile.Profile_pic %}
                <a class="nav-link rounded-circle" href="{% url 'login_app:user' %}"><img src="/media/{{user.user_profile.Profile_pic}}" alt="" width="50px" ></a>
                {% else %}
                <a class="nav-link rounded-circle" href="{% url 'login_app:user' %}"><img src="/media/demo.png" alt="" width="50px"></a>
                {% endif %}
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'login_app:edit_profile'%}">Profile</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    
      <div class="container  mt-5 mb-5">
        {% block content %}
        {% endblock %}
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

templates/posts_app/home.html
{% extends 'navbar.html'%}

{% block content %}
<h1>Home page</h1>
{% endblock %}

templates/posts_app/post.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags  %}
{% block title %}{{title}}{% endblock %}

{% block content  %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form | crispy }}
    <button type="submit">Upload</button>
</form>
{% endblock %}